webtalk_init -webtalk_dir /home/blank/fpga/Verushash2/verus_functions/verus_functions.sim/sim_1/behav/xsim/xsim.dir/aesenc_new_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec 27 21:55:04 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "03c2c080-8d7d-45e4-a86f-7ace8fb6d9fe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "430ca275252f4d98813c1f99520c3bad" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "74" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1787.878 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125716_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2839824304 -regid "" -xml /home/blank/fpga/Verushash2/verus_functions/verus_functions.sim/sim_1/behav/xsim/xsim.dir/aesenc_new_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/blank/fpga/Verushash2/verus_functions/verus_functions.sim/sim_1/behav/xsim/xsim.dir/aesenc_new_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/blank/fpga/Verushash2/verus_functions/verus_functions.sim/sim_1/behav/xsim/xsim.dir/aesenc_new_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
