#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Dec 27 21:53:10 GMT 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 430ca275252f4d98813c1f99520c3bad --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot aesenc_new_tb_behav xil_defaultlib.aesenc_new_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 430ca275252f4d98813c1f99520c3bad --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot aesenc_new_tb_behav xil_defaultlib.aesenc_new_tb xil_defaultlib.glbl -log elaborate.log

