webtalk_init -webtalk_dir /home/desktop/Documents/GIT/Verushash2/verus_functions/verus_functions.sim/sim_1/behav/xsim/xsim.dir/aesenc_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 10 08:38:44 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "410bcbfc-33ca-433b-ad2d-f09b9f84be4a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "430ca275252f4d98813c1f99520c3bad" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600 6-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2037.949 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125976_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2136829898 -regid "" -xml /home/desktop/Documents/GIT/Verushash2/verus_functions/verus_functions.sim/sim_1/behav/xsim/xsim.dir/aesenc_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/desktop/Documents/GIT/Verushash2/verus_functions/verus_functions.sim/sim_1/behav/xsim/xsim.dir/aesenc_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/desktop/Documents/GIT/Verushash2/verus_functions/verus_functions.sim/sim_1/behav/xsim/xsim.dir/aesenc_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
